In [4]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("pipeline").getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/04/14 21:46:58 WARN Utils: Your hostname, leonel-cassule, resolves to a loopback address: 127.0.1.1; using 192.168.1.80 instead (on interface wlo1)
26/04/14 21:46:58 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/14 21:47:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [11]:
def extract(file_name):
    print(f"Extracting data from {file_name}")
    return spark.read.csv(file_name)

In [14]:
#Extract data from the bmw.csv file
extracted_data = extract("datasets/bmw.csv")

Extracting data from datasets/bmw.csv

In [19]:
def transform(source_table, target_table):
    data_warehouse.sql("""CREATE TABLE {target_table} AS
    	SELECT <field-name>, <field-name>, ...
    	FROM {source_table};""")

In [21]:
# Transform the extracted_data
transformed_data = transform(extracted_data)

TypeError: transform() missing 1 required positional argument: 'target_table'

In [2]:
# Import Pandas
import pandas as pd

In [12]:
# Read in the CSV file to a DataFrame
data_frame = pd.read_csv("datasets/bmw.csv")

In [13]:
#output the first few rows
data_frame.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

In [6]:
# First, by rows
data_frame.loc[data_frame["Region"] == "Europe", :]

# Then, by columns

data_frame.loc[:,["Year", "Month", "Model", "Units_Sold"]]

      Year  Month     Model  Units_Sold
0     2018      1  3 Series        7822
1     2018      1  5 Series       10280
2     2018      1        X3        3105
3     2018      1        X5        7420
4     2018      1        X7        8474
...    ...    ...       ...         ...
3067  2025     12        X5        9281
3068  2025     12        X7       12785
3069  2025     12        i4        4906
3070  2025     12        iX        7871
3071  2025     12      MINI        6732

[3072 rows x 4 columns]

In [10]:
# Write a DataFrame to a .csv file
data_frame.to_csv("datasets/cleaned_data.csv")

In [15]:
# Use Python clientes or other tools to run SQL queries
total_sales = (
    data_frame
    .groupby("Model")["Units_Sold"]
    .sum()
    .reset_index()
)

# Extracting data from structured sources

In [6]:
import sqlalchemy
import pandas as pd

# Connection URI: schema identifier://username:password@host:port/db
#connection_uri = "postgresql+psycopg2://repl:password@localhost:5432/market"
#db_engine = sqlalchemy.create_engine(connection_uri)

# Query the SQL database
#raw_stock_data = pd.read_sql("SELECT * FROM raw_stock_data LIMIT 10", db_engine)

Transforming data with pandas

In [15]:
# Import pandas and create function extract
import pandas as pd

def extract ():
    print("Function Extract" )
    return pd.read_csv("datasets/bmw.csv")


# Extract data from the sales_data.parquet path
data_frame = extract()

def  transform(raw_data):
    # Only keep rows with 'Quantity Ordered' greater than 1
    clean_data = raw_data.loc[raw_data["Year"]> 2000,:]
    
    # Only keep columns "Month", "Model" and "Units_Sold"
    
    clean_data = clean_data.loc[:, ["Month", "Model", "Premium_Share"]]

    return  clean_data

Function Extract

In [16]:
transform(data_frame)

      Month     Model  Premium_Share
0         1  3 Series          19.12
1         1  5 Series          19.12
2         1        X3          19.12
3         1        X5          19.12
4         1        X7          19.12
...     ...       ...            ...
3067     12        X5           5.89
3068     12        X7           5.89
3069     12        i4           5.89
3070     12        iX           5.89
3071     12      MINI           5.89

[3072 rows x 3 columns]

In [10]:
data_frame.head(10)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.50,1.00
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.50,1.00
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.50,1.00
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.50,1.00
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.50,1.00
5,2018,1,Europe,i4,10607,64082,679717774,0.035,19.12,3.50,1.00
6,2018,1,Europe,iX,4805,73975,355449875,0.016,19.12,3.50,1.00
7,2018,1,Europe,MINI,2554,43005,109834770,0.013,19.12,3.50,1.00
8,2018,1,China,3 Series,3826,48068,183908168,0.021,17.60,2.37,1.02
9,2018,1,China,5 Series,7498,62435,468137630,0.015,17.60,2.37,1.02

In [16]:
raw_sales_data = extract("sales_data.csv")

def transform(raw_data):
    # Convert the "Order Date" column to type datetime
    raw_data["Order Date"] = pd.____(____, format="%m/%d/%y %H:%M")
    
    # Only keep items under ten dollars
    clean_data = raw_data.loc[____, :]
    return clean_data

clean_sales_data = transform(raw_sales_data)

# Check the data types of each column
print(____)

# ----------------------------------------
def extract(file_path):
    raw_data = pd.read_parquet(file_path)
    return raw_data

raw_sales_data = extract("sales_data.parquet")

def transform(raw_data):
  	# Filter rows and columns
    clean_data = raw_data.loc[raw_data["Quantity Ordered"] == 1, ["Order ID", "Price Each", "Quantity Ordered"]]
    return clean_data

# Transform the raw_sales_data
clean_sales_data = transform(raw_sales_data)


# Qual é o valor do preço da coluna "Price Each" dos dois itens mais caros no DataFrame transformado?
#O DataFrame clean_sales_data foi carregado para você, e você pode usar o console para explorá-lo melhor.

#clean_sales_data.nlargest(5, 'Price Each').head()




#Created by Leonel Cassul, Data Engineer

def load(clean_data, file_path):
    # Write the data to a file
    clean_data.to_csv(file_path, header=False, index= False)

    # Check to make sure the file exists
    file_exists = os.path.exists(file_path)
    if not file_exists:
        raise Exception(f"File does NOT exists at path {file_path}")

# Load the transformed data to the provided file path
load(clean_sales_data, "transformed_sales_data.csv")

TypeError: extract() takes 0 positional arguments but 1 was given

#Persisting data with pandas

In [13]:
# Persisting data with pandas,by #Leonel Cassule... Data Engineer#


# Import the os library
import pandas as pd
import sqlalchemy

def extract():
    return pd.read_csv("datasets/bmw.csv")


data_frame =  extract()

def transform(car_data):
	# Find the items prices less than 100000 euros
	return car_data.loc[car_data["Avg_Price_EUR"] < 100000, ["Revenue_EUR", "Premium_Share","Fuel_Price_Index"]]

def load(clean_data):
	# Write the data to a CSV file without the index column
	clean_data.to_csv("datasets/transformed_cars_data.csv", index=False)


clean_cars_data = transform(data_frame)

# Call the load function on the cleaned DataFrame
load(clean_cars_data)

In [15]:
#Created by Leonel Cassul, Data Enginner


# Import the os library
import pandas as pd
import os

# Load the data to a csv file with the index, no header and pipe separated
def load(clean_data, path_to_write):
	clean_data.to_csv(path_to_write, header=True, sep="|")

load(data_frame, "clean_sales_data.csv")

# Check that the file is present.
file_exists = os.path.exists("clean_sales_data.csv")
print(file_exists)

True

#Monitoring a data
pipeline

In [1]:
# Import the library

"""
Neste exercício, vamos dar uma olhada na função que você escreveu em um vídeo anterior e praticar a adição de registro à função. 
Isso ajudará você a solucionar erros ou fazer alterações na lógica!

pandas foi importado como pd. Além disso, o módulo logging foi importado e o nível de registro padrão foi definido como "debug".

Instrução!!!

Crie um registro de nível de informação após a transformação, passando a string: "Transformed 'Order Date' column to type 'datetime'."
Registre o .shape do DataFrame no nível de depuração antes e depois da filtragem.

"""
import pandas as pd
import logging
logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.DEBUG)


def transform(raw_data):
    raw_data["Order Date"] = pd.to_datetime(raw_data["Order Date"], format="%m/%d/%y %H:%M")
    clean_data = raw_data.loc[raw_data["Price Each"] < 10, :]
    
    # Create an info log regarding transformation
    logging.info("Transformed 'Order Date' column to type 'datetime'.")
    
    # Create debug-level logs for the DataFrame before and after filtering
    logging.debug(f"Shape of the DataFrame before filtering: {raw_data.shape}")
    logging.debug(f"Shape of the DataFrame after filtering: {clean_data.shape}")
    
    return clean_data
  
clean_sales_data = transform(raw_sales_data)


"""
Às vezes, seus pipelines de dados podem lançar uma exceção. Essas exceções são uma forma de alerta e permitem
que o engenheiro de dados saiba quando algo inesperado aconteceu. É importante lidar adequadamente com essas exceções.
Neste exercício, vamos praticar exatamente isso!

Para ajudar você a começar, o pandas foi importado como pd e o módulo logging foi importado. 
O nível de registro padrão foi definido como "debug".

Instrução

Atualize o pipeline para incluir um bloco try e tente ler os dados do caminho "sales_data.parquet".
Você receberá um FileNotFoundError se o arquivo não puder ser lido em um DataFrame pandas.
Crie um registro de nível de erro para documentar a falha.

""""
def extract(file_path):
    return pd.read_parquet(file_path)

# Update the pipeline to include a try block
try:
	# Attempt to read in the file
    raw_sales_data = extract("sales_data.parquet")
	
# Catch the FileNotFoundError
except FileNotFoundError as file_not_found:
	# Write an error-level log
	logging.error(file_not_found)


"""

Atualize a cláusula try-except para capturar uma cláusula KeyError e o alias como ke.
Altere o registro de nível de aviso para incluir o erro que está sendo lançado.

"""


def transform(raw_data):
	return raw_data.loc[raw_data["Total Price"] > 1000, :]

try:
	clean_sales_data = transform(raw_sales_data)
	logging.info("Successfully filtered DataFrame by 'Total Price'")
	
# Update the exception to be a KeyError, alias as ke
except KeyError as ke:
	# Log a warning-level message
	logging.warning(f"{ke}: Cannot filter DataFrame by 'Total Price'")




""" --------------Outra ideia """""

def transform(raw_data):
	return raw_data.loc[raw_data["Total Price"] > 1000, :]

try:
	clean_sales_data = transform(raw_sales_data)
	logging.info("Successfully filtered DataFrame by 'Total Price'")

except KeyError as ke:
	logging.warning(f"{ke}: Cannot filter DataFrame by 'Total Price'")
	
	# Create the "Total Price" column, transform the updated DataFrame
	raw_sales_data["Total Price"] = raw_sales_data["Price Each"] * raw_sales_data["Quantity Ordered"]
	clean_sales_data = transform(raw_sales_data)

SyntaxError: unterminated string literal (detected at line 50) (1623808377.py, line 50)